# Opacidad del fondo (0.85 es el punto óptimo entre estética y legibilidad)
background_opacity 0.85

# Permite cambiar la opacidad en tiempo real sin reiniciar la terminal
dynamic_background_opacity yes

# Difumina el texto ligeramente para que resalte sobre el fondo transparente
text_composition_strategy legacy

include ~/.config/kitty/colors.conf
